version: '3.5'

services:
  nginx:
      build: ./nginx
      ports:
        - "80:80"
      volumes:
#        - ./nginx/vhost:/etc/nginx/conf/vhost:ro
        - /Users/:/Users/
        - /Volumes/:/Volumes/
        - ./nginx/vhost:/Volumes/work/vhost:ro
      environment:
          - DEBUG=true
          - HOST_OS=mac
#      expose:
#        - "9000"
#        - "6379"
#        - "3306"
#        - "9200"
#        - "9300"
      networks:
              lnmp:
                  aliases:
                    - nginx
  php:
      build: ./php
#      ports:
#        - "9000:9000"
      volumes:
        - /Users/:/Users/
        - /Volumes/:/Volumes/
      networks:
              lnmp:
                  aliases:
                    - php
      depends_on:
            - mysql
  mysql:
      build: ./mysql
      hostname: mysqlhost
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      networks:
                  lnmp:
                      aliases:
                        - mysqlhost
  redis:
      build: ./redis
      ports:
        - "6379:6379"
      volumes:
        - /Users/:/Users/
      networks:
                  lnmp:
                      aliases:
                        - redis
networks:
  lnmp:
    driver: bridge