nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /Users/:/Users/
      - /Volumes/:/Volumes/
    environment:
        - DEBUG=true
php:
    build: ./php
    ports:
      - "9051:9051"
    volumes:
      - /Users/:/Users/
      - /Volumes/:/Volumes/
