nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /e/www/:/www/
    environment:
        - DEBUG=true
        - HOST_OS=windows
    expose:
      - "9000"
      - "6379"
      - "3306"
      - "9200"
      - "9300"
php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - /e/www/:/www/
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - /e/www/:/www/
elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /e/www/:/www/