version: '3.5'

services:
  nginx:
      build: ./nginx
      ports:
        - "80:80"
      links:
        - "php"
      volumes:
        - /www/:/www/
        - /home/:/home/
      environment:
          - DEBUG=true
          - HOST_OS=linux
      expose:
        - "9000"
        - "6379"
        - "3306"
#        - "9200"
#        - "9300"
      networks:
        lnmp:
            aliases:
              - nginx
  php:
      build: ./php
      ports:
        - "9000:9000"
      volumes:
        - /www/:/www/
        - /home/:/home/
      networks:
        lnmp:
            aliases:
              - php
  mysql:
      build: ./mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      networks:
        lnmp:
            aliases:
              - mysql
  redis:
      build: ./redis
      ports:
        - "6379:6379"
      volumes:
        - /www/:/www/
#  elasticsearch:
#      build: ./elasticsearch
#      ports:
#        - "9200:9200"
#        - "9300:9300"
#      volumes:
#        - /www/:/www/
#        - /home/:/home/
#      networks:
#              lnmp:
#                  aliases:
#                    - elasticsearch
networks:
  lnmp:
    driver: bridge